### ISSUE TITLE
Add support for going backwards through paths

### ISSUE THREAD

**Issue by baylessj** [baylessj/robotsquiggles#17]
Can't remember if this is something that should get added to path profiling or if it can be tacked on later

**Comment by Octogonapus** [comment]
Ideally, paths can include negative wheel velocities. At this point, OkapiLib is committed to supporting the following of paths in a reversed fashion, but I want to avoid having users to this if at all possible. It's always more intuitive to generate a path that has the robot go backwards than reversing a path.

We must also consider paths that include both positive and negative wheel velocities, like paths that include tight turns. I would like to see support for these paths as well.

**Comment by baylessj** [comment]
That makes sense, it had been a minute since I looked at how Okapilib handles reversing paths. I can work on supporting reversed paths.

As for supporting both positive and negative wheel velocities, that's currently supported when going forward at least :smile:

**Comment by Octogonapus** [comment]
> I can work on supporting reversed paths.

OkapiLib works by negating the target wheel velocities after the motion profile is generated, so no support is required from the motion profile generator.
