### ISSUE TITLE
Yaw incorrect in straight-line paths

### ISSUE THREAD

**Issue by dcieslak19973** [baylessj/robotsquiggles#50]
Via Okapi, generate a path similar to:

```
  c->generatePath(
      {{0_ft, 0_ft, 0_deg},
       {4_ft, 0_ft, 0_deg}},
      "foo");
```

Output will be similar to:

```
ProfilePoint: {ControlVector: {Pose: {x: 0.000000, y: 0.000000, yaw: 1.570796}, v: 0.000000, a: 2.600000, j: 0.000000}, wheels: {0.000000, 0.000000, }, k: 0.000000, t: 0.000000}
...
```

**Comment by baylessj** [comment]
This is due to the frame transformation from Okapi to Squiggles. The forward x axis in Okapi is `pi / 2` radians away from the forward x axis in the Squiggles frame. This is the expected behavior given that the debugging output you showed is coming from the Squiggles source.

**Comment by dcieslak19973** [comment]
Thanks for the reminder
